### ISSUE TITLE
Error in the field name in the in_invoice - Suppliers invoice.

### ISSUE THREAD

**Issue by alexcape14** [alexcape14/l10n-dominicana#4]
Type: General

**Describe the bug**
Odoo Version: 14
[A clear and concise description of the bug]
When you are invoicing or making a supplier invoice, it does not generate the internal sequence number, it only remains with the "/" sign of the forward slash.

**Steps to Reproduce**
1. Enter to account model
2. Create a new provider invoice
3. Safe and Confirm Invoice

**Expected behavior**
That generates the internal sequence number.

**Additional context and screenshots**
![image](https://user-images.githubusercontent.com/19417364/120147063-15443e00-c1b4-11eb-9624-979293abed62.png)

**Sample Code / Stack Trace**
```
N/A
```

**Configuration information**
Operating System:
Python version:

**Comment by cnunezd** [comment]
@alexcape14 


Error:
Odoo Server Error

Traceback (most recent call last):
  File "C:\Users\USUARIO\Documents\capw\odoo-14.0\odoo-14.0\odoo\addons\base\models\ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "C:\Users\USUARIO\Documents\capw\odoo-14.0\odoo-14.0\odoo\http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "C:\Users\USUARIO\Documents\capw\odoo-14.0\odoo-14.0\odoo\http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\Users\USUARIO\Documents\capw\odoo-14.0\odoo-14.0\odoo\service\model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\Users\USUARIO\Documents\capw\odoo-14.0\odoo-14.0\odoo\http.py", line 347, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\Users\USUARIO\Documents\capw\odoo-14.0\odoo-14.0\odoo\http.py", line 912, in __call__
    return self.method(*args, **kw)
  File "C:\Users\USUARIO\Documents\capw\odoo-14.0\odoo-14.0\odoo\http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "c:\users\usuario\documents\capw\odoo-14.0\odoo-14.0\addons\web\controllers\main.py", line 1389, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "c:\users\usuario\documents\capw\odoo-14.0\odoo-14.0\addons\web\controllers\main.py", line 1381, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\Users\USUARIO\Documents\capw\odoo-14.0\odoo-14.0\odoo\api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "C:\Users\USUARIO\Documents\capw\odoo-14.0\odoo-14.0\odoo\api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "c:\users\usuario\documents\capw\odoo-14.0\odoo-14.0\addons\account\models\account_move.py", line 1048, in onchange
    return super(AccountMove, self.with_context(recursive_onchanges=False)).onchange(values, field_name, field_onchange)
  File "C:\Users\USUARIO\Documents\capw\odoo-14.0\odoo-14.0\odoo\models.py", line 6230, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "C:\Users\USUARIO\Documents\capw\odoo-14.0\odoo-14.0\odoo\models.py", line 5986, in _onchange_eval
    method_res = method(self)
  File "c:\users\usuario\documents\capw\odoo-14.0\odoo-14.0\addons\account\models\account_move.py", line 378, in _onchange_journal
    if self.state == 'draft' and self._get_last_sequence() and self.name and self.name != '/':
  File "c:\users\usuario\documents\capw\odoo-14.0\odoo-14.0\custom-addons\l10n_do_accounting\models\account_move.py", line 536, in _get_last_sequence
    return super(AccountMove, self)._get_last_sequence(relaxed=relaxed)
  File "c:\users\usuario\documents\capw\odoo-14.0\odoo-14.0\addons\account\models\sequence_mixin.py", line 179, in _get_last_sequence
    self.env.cr.execute(query, param)
  File "<decorator-gen-3>", line 2, in execute
  File "C:\Users\USUARIO\Documents\capw\odoo-14.0\odoo-14.0\odoo\sql_db.py", line 101, in check
    return f(self, *args, **kwargs)
  File "C:\Users\USUARIO\Documents\capw\odoo-14.0\odoo-14.0\odoo\sql_db.py", line 298, in execute
    res = self._obj.execute(query, params)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\USUARIO\Documents\capw\odoo-14.0\odoo-14.0\odoo\http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\Users\USUARIO\Documents\capw\odoo-14.0\odoo-14.0\odoo\http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
psycopg2.errors.InvalidRegularExpression: la expresión regular no es válida: quantifier operand invalid

I get this error when creating an invoice/customer
